Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.define "phpweb" do |phpweb|
    phpweb.vm.network "forwarded_port", guest: 8888, host: 8888
    phpweb.vm.network "public_network", ip: "192.168.1.151"

    phpweb.vm.provision  "shell",
      inline: "apt-get update && apt-get install -y puppet"

    phpweb.vm.provision "puppet" do |puppet|
      puppet.manifests_path = "./configs/manifests"
      puppet.manifest_file = "phpweb.pp"
    end
  end
  
  config.vm.define "mysqlserver" do |mysqlserver|
    mysqlserver.vm.network "public_network", ip: "192.168.1.152"

    mysqlserver.vm.provision  "shell",
      inline: "cat /vagrant/configs/id_rsa.pub >> .ssh/authorized_keys"
  end

  config.vm.define "ansible" do |ansible|
    ansible.vm.network "public_network", ip: "192.168.1.153"

    ansible.vm.provision  "shell",
      inline: "cp /vagrant/id_rsa /home/vagrant && \
              chmod 600 /home/vagrant/id_rsa && \
              chown vagrant:vagrant /home/vagrant/id_rsa"

    ansible.vm.provision  "shell",
      inline: "apt update && \
              apt install -y software-properties-common && \
              add-apt-repository --yes --update ppa:ansible/ansible && \
              apt install -y ansible"

    ansible.vm.provision "shell",
      inline: "ansible-playbook -i /vagrant/configs/ansible/hosts \
            /vagrant/configs/ansible/playbook.yml"
  end
end
